version: '3.9'

services:
  keycloak_postgres:
      container_name: keycloak_postgres
      image: postgres:${KC_POSTGRES_VERSION}
      volumes:
        - keycloak_postgres_data:/var/lib/postgresql/data
      ports:
        - '6432:5432'
      environment:
        POSTGRES_USER: ${KC_DB_USER}
        POSTGRES_PASSWORD: ${KC_DB_PASS}
        POSTGRES_DB: ${KC_DB}

  keycloak:
    container_name: keycloak_server
    image: quay.io/keycloak/keycloak:${KC_VERSION}
    command:
      - start-dev
    environment:
      DB_VENDOR: postgres
      DB_ADDR: keycloak_postgres
      DB_DATABASE: ${KC_DB}
      DB_PORT: 6432
      DB_USER: ${KC_DB_USER}
      DB_PASSWORD: ${KC_DB_PASS}
      DB_SCHEMA: ${KC_DB_SCHEMA}
      KC_HOSTNAME: localhost
      KEYCLOAK_USER: ${KC_USER}
      KEYCLOAK_PASSWORD: ${KC_PASS}
      KEYCLOAK_ADMIN: ${KC_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PASS}
    volumes:
      - keycloak_data:/data
    ports:
      - 9191:8080
      - 9443:8443
    depends_on:
      - keycloak_postgres
#    networks:
#      - keycloak-network

volumes:
  keycloak_postgres_data:
    driver: local
  keycloak_data:
    driver: local

#networks:
#  keycloak-network