# Java Gradle CircleCI 2.0 configuration file
# See: https://circleci.com/docs/2.0/language-java/
version: 2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    machine: true
    docker:
      - image: 'cimg/openjdk:18.0.2'

    steps:
      - checkout

      - run: gradle dependencies

      # run tests!
      - run: gradle test
