version: '3.6'
services:
  users-db:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_users_volume:/var/lib/postgresql/data

volumes:
  postgres_users_volume:
    driver: local